/**
 * Set curado de iconos (lucide) para temas y dimensiones (RF-T2: ~30 iconos).
 * Se importan explícitamente para no empaquetar todo lucide.
 */
import {
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Cake,
  Calculator,
  Camera,
  Car,
  Church,
  Code,
  Coffee,
  Dog,
  Dumbbell,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HouseHeart,
  Leaf,
  Moon,
  Music,
  NotebookPen,
  Palette,
  Pen,
  Phone,
  Pill,
  Plane,
  Rocket,
  School,
  ShoppingCart,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Trophy,
  Users,
  Utensils,
  Video,
  Wallet,
} from 'lucide-react-native';

export const THEME_ICONS = {
  dumbbell: Dumbbell,
  footprints: Footprints,
  trophy: Trophy,
  stethoscope: Stethoscope,
  moon: Moon,
  'notebook-pen': NotebookPen,
  'house-heart': HouseHeart,
  users: Users,
  heart: Heart,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  school: School,
  'flower-2': Flower2,
  church: Church,
  wallet: Wallet,
  calculator: Calculator,
  briefcase: Briefcase,
  video: Video,
  rocket: Rocket,
  sparkles: Sparkles,
  coffee: Coffee,
  music: Music,
  palette: Palette,
  plane: Plane,
  car: Car,
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  bike: Bike,
  camera: Camera,
  'gamepad-2': Gamepad2,
  pill: Pill,
  baby: Baby,
  dog: Dog,
  leaf: Leaf,
  sun: Sun,
  star: Star,
  pen: Pen,
  code: Code,
  phone: Phone,
  gift: Gift,
  cake: Cake,
  tag: Tag,
} as const;

export type ThemeIconName = keyof typeof THEME_ICONS;

export const THEME_ICON_NAMES = Object.keys(THEME_ICONS) as ThemeIconName[];

export function isThemeIconName(name: string | null | undefined): name is ThemeIconName {
  return !!name && name in THEME_ICONS;
}

/** Paleta fija de 12 colores para temas propios (RF-T2). */
export const THEME_PALETTE = [
  '#4CAF50',
  '#8BC34A',
  '#009688',
  '#2196F3',
  '#3F51B5',
  '#9C27B0',
  '#E91E63',
  '#F44336',
  '#FF9800',
  '#FFC107',
  '#795548',
  '#607D8B',
] as const;
